// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDM2JneLeDDS68nVwmxwPxE8-vCEsNXk',
    appId: '1:206180211157:web:b63d78aaa1d1618ed6c55c',
    messagingSenderId: '206180211157',
    projectId: 'taskapps-2642f',
    authDomain: 'taskapps-2642f.firebaseapp.com',
    storageBucket: 'taskapps-2642f.appspot.com',
    measurementId: 'G-DW4HJNN3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDE63r0_GDX_seg9fjmEyD8SioNaED28g',
    appId: '1:206180211157:android:ec0837daf3d8954ed6c55c',
    messagingSenderId: '206180211157',
    projectId: 'taskapps-2642f',
    storageBucket: 'taskapps-2642f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFSOkhGvFkpdsZyjLxWMPQ_y5vaQ_m3g',
    appId: '1:206180211157:ios:c6ee3cf7fe0550bcd6c55c',
    messagingSenderId: '206180211157',
    projectId: 'taskapps-2642f',
    storageBucket: 'taskapps-2642f.appspot.com',
    iosBundleId: 'com.example.taskApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDM2JneLeDDS68nVwmxwPxE8-vCEsNXk',
    appId: '1:206180211157:web:fa78bf497588f849d6c55c',
    messagingSenderId: '206180211157',
    projectId: 'taskapps-2642f',
    authDomain: 'taskapps-2642f.firebaseapp.com',
    storageBucket: 'taskapps-2642f.appspot.com',
    measurementId: 'G-KTTVHYFRXG',
  );
}
